/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCS
 */
public class AfficherFacture extends javax.swing.JFrame {

    /**
     * Creates new form FactureVente
     */
    public AfficherFacture() {
        initComponents();
        setLocationRelativeTo(null);
        
        ButtonGroup1 group = new ButtonGroup1();
        group.add(jRadioButtonFactVente);
        group.add(jRadioButtonFactAchat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNumFact = new javax.swing.JTextField();
        jButtonDateAct = new javax.swing.JButton();
        jTextFieldDateFact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLigneFacture = new javax.swing.JTable();
        jButtonExit1 = new javax.swing.JButton();
        jButtonValiderFact = new javax.swing.JButton();
        jButtonAnnulerFact = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLigneFacture1 = new javax.swing.JTable();
        jButtonRefresh1 = new javax.swing.JButton();
        jButtonValiderFV = new javax.swing.JButton();
        jButtonExitFV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFournisseur1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLigneFacture2 = new javax.swing.JTable();
        jButtonRefreshFour = new javax.swing.JButton();
        jButtonValiderFA1 = new javax.swing.JButton();
        jButtonExitFV1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButtonVoirTousFacture = new javax.swing.JButton();
        jRadioButtonFactVente = new javax.swing.JRadioButton();
        jRadioButtonFactAchat = new javax.swing.JRadioButton();
        jTextFieldNumFactureAfficher = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelFactureVente = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableFactureAffiVente = new javax.swing.JTable();
        jButtonExit3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Système de gestion des stocks");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Gerer les Factures");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Développée par Ramzi HM @2024");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Construire votre Facture");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Num Facture");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Date ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Ligne Facture");

        jButtonDateAct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDateAct.setText("Date Actuelle");
        jButtonDateAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDateActActionPerformed(evt);
            }
        });

        jTableLigneFacture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NumLigne", "Nom article", "Libelle", "PrixU", "Qte", "PrixT"
            }
        ));
        jScrollPane1.setViewportView(jTableLigneFacture);

        jButtonExit1.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExit1.setText("Exit");
        jButtonExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit1ActionPerformed(evt);
            }
        });

        jButtonValiderFact.setText("Valider");
        jButtonValiderFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFactActionPerformed(evt);
            }
        });

        jButtonAnnulerFact.setText("Annuler");
        jButtonAnnulerFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerFactActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh 🔍");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonValiderFact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnnulerFact))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNumFact)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDateFact, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(116, 116, 116)
                        .addComponent(jButtonRefresh)
                        .addGap(159, 159, 159))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonExit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDateFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDateAct)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAnnulerFact)
                            .addComponent(jButtonValiderFact)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter une Facture", jPanel3);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sélectionnez le client pour lequel afficher la facture");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Client ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Facture");

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom Client", "Adresse Client"
            }
        ));
        jScrollPane2.setViewportView(jTableClient);

        jTableLigneFacture1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num Facture", "Date", "NumLigne", "Numarticle", "Libelle", "PrixU", "Qte", "PrixT"
            }
        ));
        jScrollPane4.setViewportView(jTableLigneFacture1);

        jButtonRefresh1.setText("Refresh 🔍");
        jButtonRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh1ActionPerformed(evt);
            }
        });

        jButtonValiderFV.setText("Valider");
        jButtonValiderFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFVActionPerformed(evt);
            }
        });

        jButtonExitFV.setText("Exit");
        jButtonExitFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitFVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jButtonRefresh1)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonValiderFV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExitFV)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRefresh1)
                            .addComponent(jButtonValiderFV)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonExitFV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter une Facture de vente", jPanel4);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sélectionnez le fournisseur pour lequel afficher la facture");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Fournisseur");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Facture");

        jTableFournisseur1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom Fournisseur", "Adresse Fournisseur"
            }
        ));
        jScrollPane3.setViewportView(jTableFournisseur1);

        jTableLigneFacture2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num Facture", "Date", "NumLigne", "Numarticle", "Libelle", "PrixU", "Qte", "PrixT"
            }
        ));
        jScrollPane5.setViewportView(jTableLigneFacture2);

        jButtonRefreshFour.setText("Refresh 🔍");
        jButtonRefreshFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshFourActionPerformed(evt);
            }
        });

        jButtonValiderFA1.setText("Valider");
        jButtonValiderFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFA1ActionPerformed(evt);
            }
        });

        jButtonExitFV1.setText("Exit");
        jButtonExitFV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitFV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jButtonRefreshFour)
                .addGap(45, 45, 45)
                .addComponent(jButtonValiderFA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButtonExitFV1)
                .addGap(47, 47, 47))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefreshFour)
                    .addComponent(jButtonValiderFA1)
                    .addComponent(jButtonExitFV1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1321, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 243, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 244, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Ajouter une Facture d'achat", jPanel5);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sélectionner le type de facture ");

        jButtonVoirTousFacture.setBackground(new java.awt.Color(102, 255, 102));
        jButtonVoirTousFacture.setText("Voir");
        jButtonVoirTousFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoirTousFactureActionPerformed(evt);
            }
        });

        jRadioButtonFactVente.setText("Facture de Vente");

        jRadioButtonFactAchat.setText("Facture d'Achat");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Type de Facture");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Numero Facture");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Facture de vente");

        jTableFactureAffiVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_FactVente", "Nom Client", "Adresse ", "Numero Facture", "Date", "Num Ligne", "Num Article", "Libelle", "Prix Unitaire", "Qte", "Prix Totale"
            }
        ));
        jScrollPane6.setViewportView(jTableFactureAffiVente);

        javax.swing.GroupLayout jPanelFactureVenteLayout = new javax.swing.GroupLayout(jPanelFactureVente);
        jPanelFactureVente.setLayout(jPanelFactureVenteLayout);
        jPanelFactureVenteLayout.setHorizontalGroup(
            jPanelFactureVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFactureVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFactureVenteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelFactureVenteLayout.setVerticalGroup(
            jPanelFactureVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFactureVenteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(jPanelFactureVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFactureVenteLayout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButtonExit3.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExit3.setText("Exit");
        jButtonExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonFactVente)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNumFactureAfficher, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonFactAchat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addComponent(jPanelFactureVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButtonVoirTousFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 750, Short.MAX_VALUE)
                        .addComponent(jButtonExit3)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jRadioButtonFactVente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFactAchat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumFactureAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVoirTousFacture)
                            .addComponent(jButtonExit3))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelFactureVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Afficher Tous les factures", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 606, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Étape 1 : Charger le pilote JDBC
            Class.forName("com.mysql.jdbc.Driver");

            // Étape 2 : Établir la connexion
            Connection conn = DriverManager.getConnection(url, login, pwd);
            System.out.println("Connexion réussie");

            // Étape 3 : Exécuter la requête
            String query = "SELECT id, numArt, libelle, prixU, qte, prixT FROM lignefacture";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            // Étape 4 : Ajouter les données au modèle de table
            while (rs.next()) {
                String numArt = rs.getString("numart");
                String libelle = rs.getString("libelle");
                String id = rs.getString("id");
                String prixU = rs.getString("prixU");
                String qte = rs.getString("qte");
                String prixT = rs.getString("prixT");
                
                DefaultTableModel model = (DefaultTableModel) jTableLigneFacture.getModel();
                model.addRow(new Object[]{id, numArt, libelle, prixU, qte, prixT });
            }

            // Fermer les ressources
            rs.close();
            st.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonDateActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDateActActionPerformed
        String currentDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    
    // Remplir le champ texte avec la date actuelle
            jTextFieldDateFact.setText(currentDate);
    }//GEN-LAST:event_jButtonDateActActionPerformed

    private void jButtonValiderFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFactActionPerformed
        String numFact = jTextFieldNumFact.getText().trim();
        String dateFact = jTextFieldDateFact.getText().trim();

        // Vérifier si une ligne est sélectionnée dans jTableLigneFacture
        int selectedRow = jTableLigneFacture.getSelectedRow();
        if (selectedRow != -1) {
            // Récupérer le modèle de table
            DefaultTableModel model = (DefaultTableModel) jTableLigneFacture.getModel();

            // Récupérer les valeurs des colonnes de la ligne sélectionnée
            String numLigne = model.getValueAt(selectedRow, 0).toString(); // Exemple pour la 1ère colonne
            String nomArt = model.getValueAt(selectedRow, 1).toString();  // Exemple pour la 2ème colonne
            String libelle = model.getValueAt(selectedRow, 2).toString(); // Exemple pour la 3ème colonne
            String prixU = model.getValueAt(selectedRow, 3).toString();   // Exemple pour la 4ème colonne
            String qte = model.getValueAt(selectedRow, 4).toString();     // Exemple pour la 5ème colonne
            String prixT = model.getValueAt(selectedRow, 5).toString();   // Exemple pour la 6ème colonne

            // Connexion à la base de données
            try {
                String url = "jdbc:mysql://localhost:3306/stock_manager";
                String login = "root";
                String pwd = "";
                Connection conn = DriverManager.getConnection(url, login, pwd);

                // Requête d'insertion
                String query = "INSERT INTO facture (numfact, date, numLigne, nomArt, libelle, prixU, qte, prixT) " +
                               "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(query);

                // Remplir les paramètres de la requête
                pst.setString(1, numFact);
                pst.setString(2, dateFact);
                pst.setString(3, numLigne);
                pst.setString(4, nomArt);
                pst.setString(5, libelle);
                pst.setString(6, prixU);
                pst.setString(7, qte);
                pst.setString(8, prixT);

                // Exécuter la requête
                int rowsInserted = pst.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Facture ajoutée avec succès !");
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de la facture.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

                // Fermer les ressources
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans le tableau.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonValiderFactActionPerformed

    private void jButtonAnnulerFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerFactActionPerformed
        jTextFieldNumFact.setText("");
        jTextFieldDateFact.setText("");
    }//GEN-LAST:event_jButtonAnnulerFactActionPerformed

    private void jButtonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit1ActionPerformed
       this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExit1ActionPerformed

    private void jButtonRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh1ActionPerformed
      try {
    String url = "jdbc:mysql://localhost:3306/stock_manager";
    String login = "root";
    String pwd = "";

    // Load the MySQL JDBC Driver
    Class.forName("com.mysql.jdbc.Driver");

    // Establish the connection
    try (Connection conn = DriverManager.getConnection(url, login, pwd)) {
        System.out.println("Connexion réussie");

        // Query for client data
        String clientQuery = "SELECT nomClient, adresseclient FROM client";
        String factureQuery = "SELECT numfact, date, numLigne, nomArt, libelle, prixU, qte, prixT FROM facture";

        try (Statement stmt = conn.createStatement()) {
            // Execute client query
            try (ResultSet rsClient = stmt.executeQuery(clientQuery)) {
                DefaultTableModel clientModel = (DefaultTableModel) jTableClient.getModel();
                while (rsClient.next()) {
                    String nomClient = rsClient.getString("nomClient");
                    String adresseClient = rsClient.getString("adresseclient");
                    clientModel.addRow(new Object[]{nomClient, adresseClient});
                }
            }

            // Execute facture query
            try (ResultSet rsFacture = stmt.executeQuery(factureQuery)) {
                DefaultTableModel factureModel = (DefaultTableModel) jTableLigneFacture1.getModel();
                while (rsFacture.next()) {
                    String numFact = rsFacture.getString("numfact");
                    String date = rsFacture.getString("date");
                    String numLigne = rsFacture.getString("numLigne");
                    String nomArt = rsFacture.getString("nomArt");
                    String libelle = rsFacture.getString("libelle");
                    String prixU = rsFacture.getString("prixU");
                    String qte = rsFacture.getString("qte");
                    String prixT = rsFacture.getString("prixT");
                    factureModel.addRow(new Object[]{numFact, date, numLigne, nomArt, libelle, prixU, qte, prixT});
                }
            }
        }
    }
} catch (ClassNotFoundException ex) {
    Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, "Driver not found", ex);
} catch (SQLException ex) {
    Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, "Database error", ex);
}

           
    }//GEN-LAST:event_jButtonRefresh1ActionPerformed

    private void jButtonValiderFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFVActionPerformed
       int selectedRowClient = jTableClient.getSelectedRow();
       int selectedRowFacture = jTableLigneFacture1.getSelectedRow();

    // Check if a row is selected in both tables
    if (selectedRowClient != -1 && selectedRowFacture != -1) {
        // Get the table models
        DefaultTableModel clientModel = (DefaultTableModel) jTableClient.getModel();
        DefaultTableModel factureModel = (DefaultTableModel) jTableLigneFacture1.getModel();

        // Get selected client data
        String nomClient = clientModel.getValueAt(selectedRowClient, 0).toString();
        String adresseClient = clientModel.getValueAt(selectedRowClient, 1).toString();

        // Get selected facture data
        String numFact = factureModel.getValueAt(selectedRowFacture, 0).toString();
        String dateF = factureModel.getValueAt(selectedRowFacture, 1).toString();
        String numLigne = factureModel.getValueAt(selectedRowFacture, 2).toString();
        String nomArt = factureModel.getValueAt(selectedRowFacture, 3).toString();
        String libelle = factureModel.getValueAt(selectedRowFacture, 4).toString();
        String prixU = factureModel.getValueAt(selectedRowFacture, 5).toString();
        String qte = factureModel.getValueAt(selectedRowFacture, 6).toString();
        String prixT = factureModel.getValueAt(selectedRowFacture, 7).toString();

        try {
            // Database connection details
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Connect to the database
            try (Connection conn = DriverManager.getConnection(url, login, pwd)) {
                // SQL query with placeholders
                String query = "INSERT INTO facturevente (nomClient, adresseClient, numFacture, date, numLigne, numArticle, libelle, prixU, qte, prixT) " +
                               "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                                
                // Use PreparedStatement to fill in values
                try (PreparedStatement pst = conn.prepareStatement(query)) {
                    pst.setString(1, nomClient);
                    pst.setString(2, adresseClient);
                    pst.setString(3, numFact);
                    pst.setString(4, dateF);
                    pst.setString(5, numLigne);
                    pst.setString(6, nomArt);
                    pst.setString(7, libelle);
                    pst.setString(8, prixU);
                    pst.setString(9, qte);
                    pst.setString(10, prixT);

                    // Execute the query
                    int rowsInserted = pst.executeUpdate();
                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Facture Vente ajoutée avec succès !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de la facture.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans les deux tableaux.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonValiderFVActionPerformed

    private void jButtonExitFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitFVActionPerformed
        this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitFVActionPerformed

    private void jButtonRefreshFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshFourActionPerformed
        try {
    String url = "jdbc:mysql://localhost:3306/stock_manager";
    String login = "root";
    String pwd = "";

    // Load the MySQL JDBC Driver
    Class.forName("com.mysql.jdbc.Driver");

    // Establish the connection
    try (Connection conn = DriverManager.getConnection(url, login, pwd)) {
        System.out.println("Connexion réussie");

        // Query for client data
        String clientQuery = "SELECT nomFour, adresseFour FROM fournisseur";
        String factureQuery = "SELECT numfact, date, numLigne, nomArt, libelle, prixU, qte, prixT FROM facture";

        try (Statement stmt = conn.createStatement()) {
            // Execute client query
            try (ResultSet rsClient = stmt.executeQuery(clientQuery)) {
                DefaultTableModel clientModel = (DefaultTableModel) jTableFournisseur1.getModel();
                while (rsClient.next()) {
                    String nomFour = rsClient.getString("nomFour");
                    String adresseFour = rsClient.getString("adresseFour");
                    clientModel.addRow(new Object[]{nomFour, adresseFour});
                }
            }

            // Execute facture query
            try (ResultSet rsFacture = stmt.executeQuery(factureQuery)) {
                DefaultTableModel factureModel = (DefaultTableModel) jTableLigneFacture2.getModel();
                while (rsFacture.next()) {
                    String numFact = rsFacture.getString("numfact");
                    String date = rsFacture.getString("date");
                    String numLigne = rsFacture.getString("numLigne");
                    String nomArt = rsFacture.getString("nomArt");
                    String libelle = rsFacture.getString("libelle");
                    String prixU = rsFacture.getString("prixU");
                    String qte = rsFacture.getString("qte");
                    String prixT = rsFacture.getString("prixT");
                    factureModel.addRow(new Object[]{numFact, date, numLigne, nomArt, libelle, prixU, qte, prixT});
                }
            }
        }
    }
} catch (ClassNotFoundException ex) {
    Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, "Driver not found", ex);
} catch (SQLException ex) {
    Logger.getLogger(AfficherFacture.class.getName()).log(Level.SEVERE, "Database error", ex);
}

    }//GEN-LAST:event_jButtonRefreshFourActionPerformed

    private void jButtonValiderFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFA1ActionPerformed
      int selectedRowFour = jTableFournisseur1.getSelectedRow();
      int selectedRowFacture = jTableLigneFacture1.getSelectedRow();

// Vérifiez qu'une ligne est sélectionnée dans les deux tableaux
    if (selectedRowFour != -1 && selectedRowFacture != -1) {
    
    
    // Obtenez les modèles des tableaux
    DefaultTableModel fourModel = (DefaultTableModel) jTableFournisseur1.getModel();
    DefaultTableModel factureModel = (DefaultTableModel) jTableLigneFacture1.getModel();

    // Récupérez les données du fournisseur
    String nomFour = fourModel.getValueAt(selectedRowFour, 0).toString();
    String adresseFour = fourModel.getValueAt(selectedRowFour, 1).toString();

    // Récupérez les données de la facture
    String numFact = factureModel.getValueAt(selectedRowFacture, 0).toString();
    String dateF = factureModel.getValueAt(selectedRowFacture, 1).toString();
    String numLigne = factureModel.getValueAt(selectedRowFacture, 2).toString();
    String nomArt = factureModel.getValueAt(selectedRowFacture, 3).toString();
    String libelle = factureModel.getValueAt(selectedRowFacture, 4).toString();
    String prixU = factureModel.getValueAt(selectedRowFacture, 5).toString();
    String qte = factureModel.getValueAt(selectedRowFacture, 6).toString();
    String prixT = factureModel.getValueAt(selectedRowFacture, 7).toString();

    try {
        // Connexion à la base de données
        String url = "jdbc:mysql://localhost:3306/stock_manager";
        String login = "root";
        String pwd = "";

        try (Connection conn = DriverManager.getConnection(url, login, pwd)) {
            String query = "INSERT INTO factureachat (nomFour, adresseFour, numFacture, date, numLigne, numArticle, libelle, prixU, qte, prixT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement pst = conn.prepareStatement(query)) {
                pst.setString(1, nomFour);
                pst.setString(2, adresseFour);
                pst.setString(3, numFact);
                pst.setString(4, dateF);
                pst.setString(5, numLigne);
                pst.setString(6, nomArt);
                pst.setString(7, libelle);
                pst.setString(8, prixU);
                pst.setString(9, qte);
                pst.setString(10, prixT);

                int rowsInserted = pst.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Facture Achat ajoutée avec succès !");
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de la facture.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans les deux tableaux.", "Erreur", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButtonValiderFA1ActionPerformed

    private void jButtonExitFV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitFV1ActionPerformed
         this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitFV1ActionPerformed

    private void jButtonVoirTousFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoirTousFactureActionPerformed
       
       
        
        if (jRadioButtonFactVente.isSelected()) {
            
            new jPanelFactureVente().setVisible(true);
            
            
        } else if (jRadioButtonFactAchat.isSelected()) {
             new jPanelFactureAchat().setVisible(true); // Redirection vers Frame 1
        
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une option !");
        }
    }//GEN-LAST:event_jButtonVoirTousFactureActionPerformed

    private void jButtonExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit3ActionPerformed
        this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfficherFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnnulerFact;
    private javax.swing.JButton jButtonDateAct;
    private javax.swing.JButton jButtonExit1;
    private javax.swing.JButton jButtonExit3;
    private javax.swing.JButton jButtonExitFV;
    private javax.swing.JButton jButtonExitFV1;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefresh1;
    private javax.swing.JButton jButtonRefreshFour;
    private javax.swing.JButton jButtonValiderFA1;
    private javax.swing.JButton jButtonValiderFV;
    private javax.swing.JButton jButtonValiderFact;
    private javax.swing.JButton jButtonVoirTousFacture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelFactureVente;
    private javax.swing.JRadioButton jRadioButtonFactAchat;
    private javax.swing.JRadioButton jRadioButtonFactVente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTable jTableFactureAffiVente;
    private javax.swing.JTable jTableFournisseur1;
    private javax.swing.JTable jTableLigneFacture;
    private javax.swing.JTable jTableLigneFacture1;
    private javax.swing.JTable jTableLigneFacture2;
    private javax.swing.JTextField jTextFieldDateFact;
    private javax.swing.JTextField jTextFieldNumFact;
    private javax.swing.JTextField jTextFieldNumFactureAfficher;
    // End of variables declaration//GEN-END:variables
}
