/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCS
 */
public class GererArticle extends javax.swing.JFrame {

    /**
     * Creates new form GererArticle
     */
    public GererArticle() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAjouterArt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jTextFieldNumArt = new javax.swing.JTextField();
        jTextFieldLibelle = new javax.swing.JTextField();
        jButtonExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelListeArt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeArticle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jButtonExit1 = new javax.swing.JButton();
        jPanelUpdateArt = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumArtMod = new javax.swing.JTextField();
        jTextFieldLibelleArtMod = new javax.swing.JTextField();
        jButtonExit3 = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonAnnulerMod = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonArticleRech = new javax.swing.JButton();
        jTextFieldArticleModRech = new javax.swing.JTextField();
        jPanelSupprimerArt = new javax.swing.JPanel();
        jButtonSupprimerArt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonExit2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticleSupp = new javax.swing.JTable();
        jButtonRefreshSupp = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerer Article");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Développée par Ramzi HM @2024");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero d'article:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Libelle:");

        jButtonAjouter.setBackground(new java.awt.Color(51, 255, 51));
        jButtonAjouter.setText("Ajouter ");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonAnnuler.setBackground(new java.awt.Color(255, 51, 51));
        jButtonAnnuler.setText("Annuler ");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ajouter Un Article");

        javax.swing.GroupLayout jPanelAjouterArtLayout = new javax.swing.GroupLayout(jPanelAjouterArt);
        jPanelAjouterArt.setLayout(jPanelAjouterArtLayout);
        jPanelAjouterArtLayout.setHorizontalGroup(
            jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjouterArtLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(jButtonExit))
            .addGroup(jPanelAjouterArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAnnuler)
                    .addGroup(jPanelAjouterArtLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjouter)
                            .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAjouterArtLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNumArt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAjouterArtLayout.setVerticalGroup(
            jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjouterArtLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanelAjouterArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonAnnuler))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter Article", jPanelAjouterArt);

        jTableListeArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Article", "Libelle"
            }
        ));
        jScrollPane1.setViewportView(jTableListeArticle);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liste des Article ");

        jButtonRefresh.setBackground(new java.awt.Color(255, 255, 51));
        jButtonRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRefresh.setText("Refresh 🔍✔");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonExit1.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExit1.setText("Exit");
        jButtonExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListeArtLayout = new javax.swing.GroupLayout(jPanelListeArt);
        jPanelListeArt.setLayout(jPanelListeArtLayout);
        jPanelListeArtLayout.setHorizontalGroup(
            jPanelListeArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListeArtLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 265, Short.MAX_VALUE))
            .addGroup(jPanelListeArtLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelListeArtLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelListeArtLayout.setVerticalGroup(
            jPanelListeArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListeArtLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelListeArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Liste des Articles", jPanelListeArt);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Modifier un article ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Num Article:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Libelle:");

        jButtonExit3.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExit3.setText("Exit");
        jButtonExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit3ActionPerformed(evt);
            }
        });

        jButtonModifier.setBackground(new java.awt.Color(102, 255, 102));
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonAnnulerMod.setBackground(new java.awt.Color(255, 51, 51));
        jButtonAnnulerMod.setText("Annuler");
        jButtonAnnulerMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerModActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Article A modifier:");

        jButtonArticleRech.setBackground(new java.awt.Color(255, 255, 102));
        jButtonArticleRech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonArticleRech.setText("Rechercher 🔍");
        jButtonArticleRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArticleRechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateArtLayout = new javax.swing.GroupLayout(jPanelUpdateArt);
        jPanelUpdateArt.setLayout(jPanelUpdateArtLayout);
        jPanelUpdateArtLayout.setHorizontalGroup(
            jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateArtLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jButtonExit3))
            .addGroup(jPanelUpdateArtLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldArticleModRech)
                    .addGroup(jPanelUpdateArtLayout.createSequentialGroup()
                        .addComponent(jButtonModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jButtonAnnulerMod))
                    .addComponent(jTextFieldLibelleArtMod, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumArtMod, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(43, 43, 43)
                .addComponent(jButtonArticleRech)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUpdateArtLayout.setVerticalGroup(
            jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateArtLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonExit3))
                .addGap(23, 23, 23)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArticleModRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonArticleRech))
                .addGap(51, 51, 51)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNumArtMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibelleArtMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(jPanelUpdateArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonAnnulerMod))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UpDate Article", jPanelUpdateArt);

        jButtonSupprimerArt.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSupprimerArt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSupprimerArt.setText("Supprimer");
        jButtonSupprimerArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerArtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Supprimer un article de la liste ");

        jButtonExit2.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExit2.setText("Exit");
        jButtonExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit2ActionPerformed(evt);
            }
        });

        jTableArticleSupp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Num article", "Libelle"
            }
        ));
        jScrollPane2.setViewportView(jTableArticleSupp);

        jButtonRefreshSupp.setBackground(new java.awt.Color(255, 255, 51));
        jButtonRefreshSupp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRefreshSupp.setText("Refresh 🔍");
        jButtonRefreshSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshSuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSupprimerArtLayout = new javax.swing.GroupLayout(jPanelSupprimerArt);
        jPanelSupprimerArt.setLayout(jPanelSupprimerArtLayout);
        jPanelSupprimerArtLayout.setHorizontalGroup(
            jPanelSupprimerArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupprimerArtLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButtonRefreshSupp)
                .addGap(63, 63, 63)
                .addComponent(jButtonSupprimerArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSupprimerArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSupprimerArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSupprimerArtLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                        .addComponent(jButtonExit2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelSupprimerArtLayout.setVerticalGroup(
            jPanelSupprimerArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupprimerArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSupprimerArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jButtonExit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSupprimerArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefreshSupp)
                    .addComponent(jButtonSupprimerArt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Supprimer Article", jPanelSupprimerArt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
      String numArt = jTextFieldNumArt.getText().trim();
      String libelle = jTextFieldLibelle.getText().trim();
      
      try {
        String url = "jdbc:mysql://localhost:3306/stock_manager";
        String login = "root";
        String pwd = "";

        // Étape 1 : Charger le pilote JDBC
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Étape 2 : Établir la connexion
        Connection conn = DriverManager.getConnection(url, login, pwd);
        System.out.println("Connexion réussie");

        // Étape 3 : Préparer la requête d'insertion
        String req = "INSERT INTO article ( numart, libelle ) VALUES (?, ?)";
        PreparedStatement pst = conn.prepareStatement(req);
        pst.setString(1, numArt);
         pst.setString(2, libelle);
         int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Article ajouter avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);

            // Afficher une autre interface après la création
            new GererArticle().setVisible(true);
            this.setVisible(false);
        }

        // Fermer la connexion
        pst.close();
        conn.close();

    } catch (ClassNotFoundException ex) {
        Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur de chargement du pilote JDBC.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur d'accès à la base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        jTextFieldNumArt.setText("");
        jTextFieldLibelle.setText("");
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Étape 1 : Charger le pilote JDBC
            Class.forName("com.mysql.jdbc.Driver");

            // Étape 2 : Établir la connexion
            Connection conn = DriverManager.getConnection(url, login, pwd);
            System.out.println("Connexion réussie");

            // Étape 3 : Exécuter la requête
            String query = "SELECT numart , libelle FROM article";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            // Étape 4 : Ajouter les données au modèle de table
            while (rs.next()) {
                String numArt = rs.getString("numart");
                String libelle = rs.getString("libelle");
                
                DefaultTableModel model = (DefaultTableModel) jTableListeArticle.getModel();
                model.addRow(new Object[]{numArt, libelle});
            }

            // Fermer les ressources
            rs.close();
            st.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit1ActionPerformed
        this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExit1ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit2ActionPerformed
       this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExit2ActionPerformed

    private void jButtonSupprimerArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerArtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableArticleSupp.getModel();

    // Vérifier si une ligne est sélectionnée
    int selectedRow = jTableArticleSupp.getSelectedRow();
    if (selectedRow != -1) {
        // Récupérer la valeur de la colonne "id" (ou autre clé primaire) de la ligne sélectionnée
        String id = model.getValueAt(selectedRow, 0).toString(); 

        // Demander confirmation
        int response = JOptionPane.showConfirmDialog(
            this,
            "Voulez-vous vraiment supprimer cette ligne ?",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION
        );

        // Si l'utilisateur confirme
        if (response == JOptionPane.YES_OPTION) {
            try {
                // Connexion à la base de données
                String url = "jdbc:mysql://localhost:3306/stock_manager";
                String login = "root";
                String pwd = "";
                Connection conn = DriverManager.getConnection(url, login, pwd);

                // Supprimer la ligne de la base de données
                String query = "DELETE FROM article WHERE id = ?";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, id);
                int rowsAffected = pst.executeUpdate();

                // Vérifier si la suppression a réussi
                if (rowsAffected > 0) {
                    // Supprimer la ligne du modèle de table
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Article supprimé avec succès !");
                } else {
                    JOptionPane.showMessageDialog(this, "Échec de la suppression dans la base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

                // Fermer les ressources
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne à supprimer.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonSupprimerArtActionPerformed

    private void jButtonExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit3ActionPerformed
         this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExit3ActionPerformed

    private void jButtonRefreshSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshSuppActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Étape 1 : Charger le pilote JDBC
            Class.forName("com.mysql.jdbc.Driver");

            // Étape 2 : Établir la connexion
            Connection conn = DriverManager.getConnection(url, login, pwd);
            System.out.println("Connexion réussie");

            // Étape 3 : Exécuter la requête
            String query = "SELECT id, numart, libelle FROM article";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            // Étape 4 : Ajouter les données au modèle de table
            while (rs.next()) {
                String id = rs.getString("id");
                String numArt = rs.getString("numart");
                String libelle = rs.getString("libelle");
                
                
                DefaultTableModel model = (DefaultTableModel) jTableArticleSupp.getModel();
                model.addRow(new Object[]{id, numArt, libelle });
            }

            // Fermer les ressources
            rs.close();
            st.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshSuppActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
    String updatedNumArt = jTextFieldNumArtMod.getText();
    String updatedLibelle = jTextFieldLibelleArtMod.getText();
    String currentNumArt = jTextFieldArticleModRech.getText();

    try {
        String url = "jdbc:mysql://localhost:3306/stock_manager";
        String login = "root";
        String pwd = "";

        // Step 1: Load the driver
        Class.forName("com.mysql.jdbc.Driver");

        // Step 2: Establish the connection
        Connection conn = DriverManager.getConnection(url, login, pwd);
        

        // Step 3: Prepare the SQL Update query
        String updateQuery = "UPDATE article SET numart = ?, libelle = ? WHERE numart = ?";

        // Step 4: Use PreparedStatement to update
        PreparedStatement pstmt = conn.prepareStatement(updateQuery);
        pstmt.setString(1, updatedNumArt);
        pstmt.setString(2, updatedLibelle);
         pstmt.setString(3, currentNumArt);
       

        // Step 5: Execute the update
        int rowsAffected = pstmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Step 6: Close resources
        pstmt.close();
        conn.close();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonAnnulerModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerModActionPerformed
         jTextFieldNumArtMod.setText("");
        jTextFieldLibelleArtMod.setText("");
    }//GEN-LAST:event_jButtonAnnulerModActionPerformed

    private void jButtonArticleRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArticleRechActionPerformed
                                                        
        String numArt = jTextFieldArticleModRech.getText();
       

   try {
            String url="jdbc:mysql://localhost:3306/stock_manager";
            String login="root";
            String pwd="";

            // Step1: Chargement du pilote
            Class.forName("com.mysql.jdbc.Driver");
            
            // Step2: etablissement de la connection
            Connection conn =  DriverManager.getConnection(url,login,pwd);
            System.out.println("its OK");
            
            // Step3: preparation  
            Statement st = conn.createStatement();
            
           
           // Step4.4:  execution de la requete de selection
            String req = "SELECT * FROM article WHERE numart = '" + numArt + "'";
            ResultSet rs = st.executeQuery(req);
            boolean exist= false;
            String numArt1 = "", libelle1 = "";
            while( rs.next()){
                exist = true;
                numArt1 = rs.getString("numart");
                libelle1 = rs.getString("libelle"); 
                   }
            
            if(exist == true){
                JOptionPane.showMessageDialog(this, "Article Found !", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            
            jTextFieldNumArtMod.setText(numArt1);
            jTextFieldLibelleArtMod.setText(libelle1);
           
            
            }else{
                JOptionPane.showMessageDialog(this, "Not Found ! Try Again", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererArticle.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButtonArticleRechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonAnnulerMod;
    private javax.swing.JButton jButtonArticleRech;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExit1;
    private javax.swing.JButton jButtonExit2;
    private javax.swing.JButton jButtonExit3;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefreshSupp;
    private javax.swing.JButton jButtonSupprimerArt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAjouterArt;
    private javax.swing.JPanel jPanelListeArt;
    private javax.swing.JPanel jPanelSupprimerArt;
    private javax.swing.JPanel jPanelUpdateArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableArticleSupp;
    private javax.swing.JTable jTableListeArticle;
    private javax.swing.JTextField jTextFieldArticleModRech;
    private javax.swing.JTextField jTextFieldLibelle;
    private javax.swing.JTextField jTextFieldLibelleArtMod;
    private javax.swing.JTextField jTextFieldNumArt;
    private javax.swing.JTextField jTextFieldNumArtMod;
    // End of variables declaration//GEN-END:variables
}
