/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCS
 */
public class GererClient extends javax.swing.JFrame {

    /**
     * Creates new form GererClient
     */
    public GererClient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomCli = new javax.swing.JTextField();
        jTextFieldAdresseCli = new javax.swing.JTextField();
        jTextFieldContactCli = new javax.swing.JTextField();
        jButtonValideAjou = new javax.swing.JButton();
        jButtonAnnulerAjou = new javax.swing.JButton();
        jButtonExitAjou = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButtonRefreshListe = new javax.swing.JButton();
        jButtonExitListe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeClient = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButtonExitUpdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIdClientMod = new javax.swing.JTextField();
        jButtonRechercherMod = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNomClientMod = new javax.swing.JTextField();
        jTextFieldAdresseClientMod = new javax.swing.JTextField();
        jTextFieldContactClientMod = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jButtonAnnulerMod = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRefreshSupp = new javax.swing.JButton();
        jButtonExitSupp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSupprimerCli = new javax.swing.JTable();
        jButtonSupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Développée par Ramzi HM @2024");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerer nos Client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ajouter un Client");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nom Client :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Adresse Client :");

        jTextFieldContactCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactCliActionPerformed(evt);
            }
        });

        jButtonValideAjou.setBackground(new java.awt.Color(102, 255, 102));
        jButtonValideAjou.setText("Valider");
        jButtonValideAjou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValideAjouActionPerformed(evt);
            }
        });

        jButtonAnnulerAjou.setBackground(new java.awt.Color(255, 51, 51));
        jButtonAnnulerAjou.setText("Annuler");
        jButtonAnnulerAjou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerAjouActionPerformed(evt);
            }
        });

        jButtonExitAjou.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExitAjou.setText("Exit");
        jButtonExitAjou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitAjouActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Contact Client :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomCli)
                    .addComponent(jTextFieldAdresseCli)
                    .addComponent(jTextFieldContactCli)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonValideAjou)
                                .addGap(49, 49, 49)
                                .addComponent(jButtonAnnulerAjou)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonExitAjou)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAdresseCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContactCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnulerAjou)
                    .addComponent(jButtonValideAjou))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jButtonExitAjou)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Ajouter un client", jPanel3);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Liste des clients ");

        jButtonRefreshListe.setBackground(new java.awt.Color(255, 255, 102));
        jButtonRefreshListe.setText("Refresh 🔍");
        jButtonRefreshListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshListeActionPerformed(evt);
            }
        });

        jButtonExitListe.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExitListe.setText("Exit");
        jButtonExitListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitListeActionPerformed(evt);
            }
        });

        jTableListeClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom Client", "Adresse Client", "Contact Client"
            }
        ));
        jScrollPane1.setViewportView(jTableListeClient);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRefreshListe)
                        .addGap(144, 144, 144)
                        .addComponent(jButtonExitListe))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefreshListe)
                    .addComponent(jButtonExitListe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Liste des clients", jPanel4);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Modifier les informations d'un client");

        jButtonExitUpdate.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExitUpdate.setText("Exit");
        jButtonExitUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitUpdateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Id  Client : ");

        jButtonRechercherMod.setBackground(new java.awt.Color(255, 255, 102));
        jButtonRechercherMod.setText("Rechercher");
        jButtonRechercherMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercherModActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nom Client :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Adresse Client :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Contact Client :");

        jButtonModifier.setBackground(new java.awt.Color(102, 255, 51));
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonAnnulerMod.setBackground(new java.awt.Color(255, 51, 51));
        jButtonAnnulerMod.setText("Annuler");
        jButtonAnnulerMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonExitUpdate))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIdClientMod))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomClientMod)
                            .addComponent(jTextFieldAdresseClientMod)
                            .addComponent(jTextFieldContactClientMod)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jButtonRechercherMod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jButtonModifier)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonAnnulerMod)))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExitUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdClientMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRechercherMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldNomClientMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addComponent(jTextFieldAdresseClientMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldContactClientMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonAnnulerMod))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("UpDate information client", jPanel6);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Supprimer un Client de la liste");

        jButtonRefreshSupp.setBackground(new java.awt.Color(255, 255, 102));
        jButtonRefreshSupp.setText("Refresh 🔍");
        jButtonRefreshSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshSuppActionPerformed(evt);
            }
        });

        jButtonExitSupp.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExitSupp.setText("Exit");
        jButtonExitSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitSuppActionPerformed(evt);
            }
        });

        jTableSupprimerCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nom Client", "Adresse Client", "Contact Client"
            }
        ));
        jScrollPane2.setViewportView(jTableSupprimerCli);

        jButtonSupprimer.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRefreshSupp)
                        .addGap(158, 158, 158)
                        .addComponent(jButtonExitSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButtonSupprimer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitSupp)
                    .addComponent(jButtonRefreshSupp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSupprimer)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Supprimer un client", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContactCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactCliActionPerformed

    private void jButtonAnnulerAjouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerAjouActionPerformed
        jTextFieldNomCli.setText("");
        jTextFieldAdresseCli.setText("");
        jTextFieldContactCli.setText("");
    }//GEN-LAST:event_jButtonAnnulerAjouActionPerformed

    private void jButtonValideAjouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValideAjouActionPerformed
       String nomClient = jTextFieldNomCli.getText().trim();
       String adresseClient = jTextFieldAdresseCli.getText().trim();
       String contactClient = jTextFieldContactCli.getText().trim();

      
      try {
        String url = "jdbc:mysql://localhost:3306/stock_manager";
        String login = "root";
        String pwd = "";

        // Étape 1 : Charger le pilote JDBC
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Étape 2 : Établir la connexion
        Connection conn = DriverManager.getConnection(url, login, pwd);
        System.out.println("Connexion réussie");

        // Étape 3 : Préparer la requête d'insertion
        String req = "INSERT INTO client ( nomClient, adresseClient, contactClient ) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(req);
        pst.setString(1, nomClient);
        pst.setString(2, adresseClient);
        pst.setString(3, contactClient);
         int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Client ajouter avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);

            // Afficher une autre interface après la création
            new GererClient().setVisible(true);
            this.setVisible(false);
        }

        // Fermer la connexion
        pst.close();
        conn.close();

    } catch (ClassNotFoundException ex) {
        Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur de chargement du pilote JDBC.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur d'accès à la base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonValideAjouActionPerformed

    private void jButtonExitAjouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitAjouActionPerformed
      this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitAjouActionPerformed

    private void jButtonRefreshListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshListeActionPerformed
       try {
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Étape 1 : Charger le pilote JDBC
            Class.forName("com.mysql.jdbc.Driver");

            // Étape 2 : Établir la connexion
            Connection conn = DriverManager.getConnection(url, login, pwd);
            System.out.println("Connexion réussie");

            // Étape 3 : Exécuter la requête
            String query = "SELECT id, nomClient , adresseclient , contactClient FROM client";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            // Étape 4 : Ajouter les données au modèle de table
            while (rs.next()) {
                String id = rs.getString("id");
                String nomCli = rs.getString("nomClient");
                String adresseCli = rs.getString("adresseclient");
                String contactCli = rs.getString("contactClient");
                
                DefaultTableModel model = (DefaultTableModel) jTableListeClient.getModel();
                model.addRow(new Object[]{id, nomCli, adresseCli, contactCli });
            }

            // Fermer les ressources
            rs.close();
            st.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshListeActionPerformed

    private void jButtonExitListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitListeActionPerformed
      this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitListeActionPerformed

    private void jButtonRefreshSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshSuppActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/stock_manager";
            String login = "root";
            String pwd = "";

            // Étape 1 : Charger le pilote JDBC
            Class.forName("com.mysql.jdbc.Driver");

            // Étape 2 : Établir la connexion
            Connection conn = DriverManager.getConnection(url, login, pwd);
            System.out.println("Connexion réussie");

            // Étape 3 : Exécuter la requête
            String query = "SELECT id, nomClient, adresseClient, contactClient FROM client";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            // Étape 4 : Ajouter les données au modèle de table
            while (rs.next()) {
                String id = rs.getString("id");
                String nomCli = rs.getString("nomClient");
                String adresseCli = rs.getString("adresseClient");
                String contactCli = rs.getString("contactClient");
                
                
                DefaultTableModel model = (DefaultTableModel) jTableSupprimerCli.getModel();
                model.addRow(new Object[]{id, nomCli, adresseCli, contactCli  });
            }

            // Fermer les ressources
            rs.close();
            st.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshSuppActionPerformed

    private void jButtonExitSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitSuppActionPerformed
        this.dispose();
      MainUIStock mainUIStock = new MainUIStock();
      mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitSuppActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableSupprimerCli.getModel();

    // Vérifier si une ligne est sélectionnée
    int selectedRow = jTableSupprimerCli.getSelectedRow();
    if (selectedRow != -1) {
        // Récupérer la valeur de la colonne "id" (ou autre clé primaire) de la ligne sélectionnée
        String id = model.getValueAt(selectedRow, 0).toString(); 

        // Demander confirmation
        int response = JOptionPane.showConfirmDialog(
            this,
            "Voulez-vous vraiment supprimer cette ligne ?",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION
        );

        // Si l'utilisateur confirme
        if (response == JOptionPane.YES_OPTION) {
            try {
                // Connexion à la base de données
                String url = "jdbc:mysql://localhost:3306/stock_manager";
                String login = "root";
                String pwd = "";
                Connection conn = DriverManager.getConnection(url, login, pwd);

                // Supprimer la ligne de la base de données
                String query = "DELETE FROM client WHERE id = ?";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, id);
                int rowsAffected = pst.executeUpdate();

                // Vérifier si la suppression a réussi
                if (rowsAffected > 0) {
                    // Supprimer la ligne du modèle de table
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Client supprimé avec succès !");
                } else {
                    JOptionPane.showMessageDialog(this, "Échec de la suppression dans la base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

                // Fermer les ressources
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne à supprimer.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonExitUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitUpdateActionPerformed
         this.dispose();
         MainUIStock mainUIStock = new MainUIStock();
         mainUIStock.setVisible(true);
    }//GEN-LAST:event_jButtonExitUpdateActionPerformed

    private void jButtonRechercherModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercherModActionPerformed
                                                         
        String idClient = jTextFieldIdClientMod.getText();
       

   try {
            String url="jdbc:mysql://localhost:3306/stock_manager";
            String login="root";
            String pwd="";

            // Step1: Chargement du pilote
            Class.forName("com.mysql.jdbc.Driver");
            
            // Step2: etablissement de la connection
            Connection conn =  DriverManager.getConnection(url,login,pwd);
            System.out.println("its OK");
            
            // Step3: preparation  
            Statement st = conn.createStatement();
            
           
           // Step4.4:  execution de la requete de selection
            String req = "SELECT * FROM client WHERE id = '" + idClient + "'";
            ResultSet rs = st.executeQuery(req);
            boolean exist= false;
            String NomCli = "", AdresseCli = "", ContactCli = "";
            while( rs.next()){
                exist = true;
                NomCli = rs.getString("nomClient");
                AdresseCli = rs.getString("adresseClient"); 
                ContactCli = rs.getString("contactClient"); 
                   }
            
            if(exist == true){
                JOptionPane.showMessageDialog(this, "Client Found !", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            
            jTextFieldNomClientMod.setText(NomCli);
            jTextFieldAdresseClientMod.setText(AdresseCli);
            jTextFieldContactClientMod.setText(ContactCli);
           
            
            }else{
                JOptionPane.showMessageDialog(this, "Not Found ! Try Again", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButtonRechercherModActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        String updatedNomCli =  jTextFieldNomClientMod.getText();
        String updatedAdresseCli = jTextFieldAdresseClientMod.getText();
        String updatedContactCli = jTextFieldContactClientMod.getText();
        String idClient = jTextFieldIdClientMod.getText();

    try {
        String url = "jdbc:mysql://localhost:3306/stock_manager";
        String login = "root";
        String pwd = "";

        // Step 1: Load the driver
        Class.forName("com.mysql.jdbc.Driver");

        // Step 2: Establish the connection
        Connection conn = DriverManager.getConnection(url, login, pwd);
        

        // Step 3: Prepare the SQL Update query
        String updateQuery = "UPDATE client SET nomClient = ?, adresseClient = ? , contactClient = ? WHERE id = ?";

        // Step 4: Use PreparedStatement to update
        PreparedStatement pstmt = conn.prepareStatement(updateQuery);
        pstmt.setString(1, updatedNomCli);
        pstmt.setString(2, updatedAdresseCli);
        pstmt.setString(3, updatedContactCli);
        pstmt.setString(4, idClient);
       

        // Step 5: Execute the update
        int rowsAffected = pstmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Step 6: Close resources
        pstmt.close();
        conn.close();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(GererClient.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonAnnulerModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerModActionPerformed
         jTextFieldNomClientMod.setText("");
         jTextFieldAdresseClientMod.setText("");
         jTextFieldContactClientMod.setText("");
    }//GEN-LAST:event_jButtonAnnulerModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAjouter1;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonAnnuler1;
    private javax.swing.JButton jButtonAnnulerAjou;
    private javax.swing.JButton jButtonAnnulerMod;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExit1;
    private javax.swing.JButton jButtonExitAjou;
    private javax.swing.JButton jButtonExitListe;
    private javax.swing.JButton jButtonExitSupp;
    private javax.swing.JButton jButtonExitUpdate;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRechercherMod;
    private javax.swing.JButton jButtonRefreshListe;
    private javax.swing.JButton jButtonRefreshSupp;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JButton jButtonValideAjou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAjouterArt;
    private javax.swing.JPanel jPanelAjouterArt1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableListeClient;
    private javax.swing.JTable jTableSupprimerCli;
    private javax.swing.JTextField jTextFieldAdresseCli;
    private javax.swing.JTextField jTextFieldAdresseClientMod;
    private javax.swing.JTextField jTextFieldContactCli;
    private javax.swing.JTextField jTextFieldContactClientMod;
    private javax.swing.JTextField jTextFieldIdClientMod;
    private javax.swing.JTextField jTextFieldLibelle;
    private javax.swing.JTextField jTextFieldLibelle1;
    private javax.swing.JTextField jTextFieldNomCli;
    private javax.swing.JTextField jTextFieldNomClientMod;
    private javax.swing.JTextField jTextFieldNumArt;
    private javax.swing.JTextField jTextFieldNumArt1;
    // End of variables declaration//GEN-END:variables
}
